name: live_free
description: Finance tracker

publish_to: 'none'

version: 0.0.0  # change in lib/core/constants

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Env
  flutter_dotenv: ^5.0.2

  # Local Storage
  hive_flutter: ^1.1.0

  # Logging
  loggy: ^2.0.1

  # Networking
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+3

  # Routing
  vrouter: ^1.2.0+14

  # Service Locator
  get_it: ^7.2.0

  # State Management
  flutter_riverpod: ^0.14.0+3

  # UI
  currency_text_input_formatter: ^2.1.5

  # Util
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  fpdart: ^0.0.11
  intl: ^0.17.0
  numeric_keyboard: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint
#  lint: ^1.5.3
  lint: ^1.7.2

  # Generators

  # Hive
  #  build_runner: ^2.0.4
  #  hive_generator: ^1.1.0

  # App Icon Generator:  flutter pub run flutter_launcher_icons:main -f flutter_launcher_icons.yaml
  flutter_launcher_icons: ^0.9.2

  # Splash Screen:  flutter pub run flutter_native_splash:create --path=flutter_native_splash.yaml
  flutter_native_splash: ^1.2.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
